services:
  web:
    build: ./frontend
    container_name: next_dev
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
    depends_on:
      - app

  app:
    build: .
    container_name: backend_api_dev
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80
    volumes:
      - .:/backend
    depends_on:
      - db
  
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: exampledb

  # adminer:
  #   image: adminer
  #   restart: always
  #   depends_on:
  #     - db
  #   ports:
  #     - 8080:8080
      
  

  


